module tests/helper

import io

pub fun star-wars()
  echo("A long, long time ago ")
  echo("in a galaxy far, far away ")

pub fun jar-jar()
  echo("Mesa culled Jar Jar Binks ")
  echo("Mesa your humble servant ")

pub fun unix()
  echo("UNIX is basically ")
  echo("a simple operating system, ")
  echo("but ")
  echo("you have to be a genius to understand the simplicity.\n")

pub fun hamlet()
  echo("To be, or not to be, ")
  echo("that is the question:\n")
  echo("Whether 'tis nobler in the mind to suffer\n")